# Generated by Django 3.0.6 on 2021-09-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato_contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contrato', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=20)),
                ('precio_acordado', models.IntegerField(max_length=30)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dato_empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fiscal', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=13)),
                ('tel_empresa', models.IntegerField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('tel_responsable', models.IntegerField(max_length=30)),
                ('observaciones', models.CharField(max_length=200)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo_encargado', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='dato_empresa',
            name='nombre_proveedores',
            field=models.ManyToManyField(to='Contratos.Proveedores'),
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='estado',
            field=models.ManyToManyField(to='Contratos.Estado'),
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='nombre_departamento',
            field=models.ManyToManyField(to='Contratos.Departamento'),
        ),
    ]
