# Generated by Django 3.0.6 on 2021-09-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0002_auto_20210928_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_empresa',
            name='telefono',
        ),
    ]
