# Generated by Django 3.0.6 on 2021-09-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0003_remove_dato_empresa_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_contrato',
            name='seccion',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='correo_encargado',
            field=models.EmailField(max_length=254, verbose_name='Correo Encargado'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Departamento'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=10, verbose_name='Estado Contrato'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Prooverdor'),
        ),
    ]
