# Generated by Django 3.0.6 on 2021-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0004_auto_20210928_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_contrato',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='nombre_contrato',
            field=models.CharField(max_length=30, verbose_name='Nombre Contrato'),
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='precio_acordado',
            field=models.IntegerField(max_length=30, verbose_name='Precio Servicio'),
        ),
    ]
