# Generated by Django 3.0.6 on 2021-09-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0006_auto_20210928_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_empresa',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_contrato'),
        ),
    ]
