# Generated by Django 3.0.6 on 2021-09-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0007_dato_empresa_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_contrato',
            name='nombre_contrato',
            field=models.CharField(max_length=30),
        ),
    ]
