# Generated by Django 3.0.6 on 2021-09-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0008_auto_20210928_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_empresa',
            name='contrato',
        ),
    ]
