# Generated by Django 3.0.6 on 2021-09-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0010_dato_empresa_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dato_contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='dato_empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='precio_acordado',
            field=models.CharField(max_length=10, verbose_name='Precio Servicio'),
        ),
        migrations.AlterField(
            model_name='dato_empresa',
            name='tel_empresa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dato_empresa',
            name='tel_responsable',
            field=models.CharField(max_length=20),
        ),
    ]
