# Generated by Django 3.0.6 on 2021-09-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0011_auto_20210928_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_empresa',
            name='nombre_responsable',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
