# Generated by Django 3.0.6 on 2021-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0012_dato_empresa_nombre_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono_empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_empresa', models.CharField(max_length=20)),
            ],
        ),
    ]
