# Generated by Django 3.0.6 on 2021-09-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0013_telefono_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_empresa',
            name='contrato',
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_empresa'),
        ),
    ]
