# Generated by Django 3.0.6 on 2021-09-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0014_auto_20210929_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato_empresa',
            old_name='tel_empresa',
            new_name='telefono_empresa',
        ),
        migrations.RenameField(
            model_name='dato_empresa',
            old_name='tel_responsable',
            new_name='telefono_responsable',
        ),
        migrations.RemoveField(
            model_name='dato_empresa',
            name='nombre_responsable',
        ),
        migrations.AddField(
            model_name='dato_empresa',
            name='nombre_responsable',
            field=models.ManyToManyField(to='Contratos.Telefono_empresa'),
        ),
    ]
