# Generated by Django 3.0.6 on 2021-09-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0016_auto_20210929_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nombre_representante',
            options={'verbose_name': 'Representante', 'verbose_name_plural': 'Representantes'},
        ),
        migrations.RemoveField(
            model_name='dato_contrato',
            name='precio_acordado',
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='duracion_periodo',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='periodos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='precio_final',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='precio_periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
