# Generated by Django 3.0.6 on 2021-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0017_auto_20210929_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_contrato',
            name='duracion_periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
