# Generated by Django 3.0.6 on 2021-09-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0018_auto_20210929_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato_the_fives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hotel', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_representante', models.CharField(max_length=30)),
                ('telefono_responsable', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dato_empresa',
            new_name='Dato_proveedor',
        ),
        migrations.AlterModelOptions(
            name='dato_proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_proveedor'),
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_the_fives'),
        ),
    ]
