# Generated by Django 3.0.6 on 2021-10-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0021_auto_20210929_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dato_the_fives',
            options={'verbose_name': 'Empresa The Five'},
        ),
        migrations.RemoveField(
            model_name='dato_contrato',
            name='empresa',
        ),
    ]
