# Generated by Django 3.0.6 on 2021-10-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0022_auto_20211004_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_the_fives'),
        ),
    ]
