# Generated by Django 3.0.6 on 2021-10-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0023_dato_contrato_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_contrato',
            name='proveedor',
        ),
    ]
