# Generated by Django 3.0.6 on 2021-10-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0024_remove_dato_contrato_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_contrato',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='dato_proveedor',
            name='nombre_representante',
        ),
    ]
