# Generated by Django 3.0.6 on 2021-10-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0025_auto_20211004_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_the_fives'),
        ),
        migrations.AddField(
            model_name='dato_contrato',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contratos.Dato_proveedor'),
        ),
        migrations.AddField(
            model_name='dato_proveedor',
            name='nombre_representante',
            field=models.ManyToManyField(to='Contratos.Nombre_representante'),
        ),
    ]
