# Generated by Django 3.0.6 on 2021-10-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0026_auto_20211004_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_the_fives',
            name='razon_comercial',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dato_the_fives',
            name='rfc',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='dato_the_fives',
            name='razon_social',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
