# Generated by Django 3.0.6 on 2021-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0028_auto_20211004_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_proveedor',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
