# Generated by Django 3.0.6 on 2021-10-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0029_auto_20211004_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_proveedor',
            name='observaciones',
            field=models.TextField(max_length=200),
        ),
    ]
