# Generated by Django 3.0.6 on 2021-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0030_auto_20211004_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato_proveedor',
            old_name='telefono_responsable',
            new_name='telefono_representante',
        ),
    ]
