# Generated by Django 3.0.6 on 2021-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0032_dato_contrato_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_contrato',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
