# Generated by Django 3.0.6 on 2021-10-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0033_dato_contrato_datetimeofupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato_contrato',
            old_name='dateTimeOfUpload',
            new_name='fecha_subida_documento',
        ),
    ]
