# Generated by Django 3.2.7 on 2021-10-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0038_auto_20211006_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_contrato',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
