# Generated by Django 3.2.7 on 2021-10-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0040_auto_20211007_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_contrato',
            name='deleted',
        ),
    ]
