# Generated by Django 3.2.7 on 2021-10-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0041_remove_dato_contrato_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato_contrato',
            old_name='fecha_subida_documento',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='dato_proveedor',
            old_name='nombre_proveedores',
            new_name='nombre_proveedor',
        ),
    ]
