# Generated by Django 3.2.7 on 2021-10-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0042_auto_20211015_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_contrato',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificación'),
        ),
    ]
