# Generated by Django 3.2.7 on 2021-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0043_alter_dato_contrato_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.BooleanField(max_length=10, verbose_name='Estado Contrato'),
        ),
    ]
