# Generated by Django 3.2.7 on 2021-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0044_alter_estado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.BooleanField(verbose_name='Estado Contrato'),
        ),
    ]
