# Generated by Django 3.2.7 on 2021-10-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0046_alter_estado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Contratos.dato_the_fives', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='dato_contrato',
            name='nombre_contrato',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dato_proveedor',
            name='rfc',
            field=models.CharField(max_length=13, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='dato_the_fives',
            name='rfc',
            field=models.CharField(max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
